### ISSUE TITLE
Unable to execute script

### ISSUE THREAD

**Issue by pmarkiewicz** [mf0o/crsf_SA_lua#1]
OpenTx 2.3.11
Radiomaster TX 16S

I got errors while run debug.lua
drawscreentitle  is fresh run, 
?:0 when there is luac file.

![IMG_20210505_113940](https://user-images.githubusercontent.com/483107/117123387-3cffdc00-ad97-11eb-867b-90996883fbf1.jpg)
![IMG_20210505_113859](https://user-images.githubusercontent.com/483107/117123397-40936300-ad97-11eb-8928-7b8978a1c45a.jpg)

**Comment by pmarkiewicz** [comment]
OK, looks like TX16s isn't supported, just needs more work

**Comment by mf0o** [comment]
Hi.
Thank you for your feedback.
Yes, indeed the debug.lua script is the X9D version and that doesnt work on TX16.

The actual smartaudio lua should work on the TX16. Its just to find the right addresses.
We can debug this and add TX16 support if you like, just let me know.

**Comment by pmarkiewicz** [comment]
I have working solution on TX16S, I'll do pull req tomorrow so you can check Taranis
